import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.99.1/+esm';

const supabase = createClient('https://gwxfjxbpeymffnzjaasw.supabase.co', 'sb_publishable_OIItBfn6q9t4OSQ4lJKcgg_4StQc-KT');
const app = document.querySelector('#app');
const toastNode = document.querySelector('#toast');
let session = null, profile = null, view = 'dashboard', tasks = [], staff = [], selected = null;
const statusLabel = { new:'Baru', work:'Dikerjakan', review:'Menunggu verifikasi', revise:'Perlu revisi', done:'Selesai' };
const date = v => v ? new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)) : 'Tanpa deadline';
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const isAdmin = () => profile?.role === 'admin';
const scoreInfo = t => { const c=t.task_checklists||[]; const total=c.reduce((n,x)=>n+Number(x.score||1),0); const complete=c.filter(x=>x.completed).reduce((n,x)=>n+Number(x.score||1),0); return {total,complete,percent:total?Math.round(complete/total*100):0}; };
const progressBar = t => { const s=scoreInfo(t); return `<div class="progress" aria-label="Progress ${s.percent}%"><i style="width:${s.percent}%"></i></div><span class="score">${s.complete}/${s.total} poin · ${s.percent}%</span>`; };
function toast(message, error=false){ toastNode.textContent=message; toastNode.style.background=error?'#b42318':'#17313a'; toastNode.classList.add('show'); setTimeout(()=>toastNode.classList.remove('show'),3500); }
function err(e){ console.error(e); toast(e?.message || 'Terjadi kesalahan. Silakan coba lagi.', true); }
function status(s){ return `<span class="badge ${s}">${statusLabel[s]||s}</span>`; }
function shell(content){
  const tabs=[['dashboard','Ringkasan'],['tasks',isAdmin()?'Semua tugas':'Tugas saya'],['reports','Laporan'],['people','Staff']].filter(([id])=>id!=='people'||isAdmin());
  return `<main class="shell"><header class="topbar"><div class="mark"><span class="logo">✓</span>Namichii Task</div><div class="user"><b>${esc(profile.full_name||session.user.email)}</b><br><span class="muted">${isAdmin()?'Administrator':'Staff'}</span> · <button class="btn secondary" data-action="logout">Keluar</button></div></header><nav class="nav">${tabs.map(([id,label])=>`<button class="${view===id?'active':''}" data-view="${id}">${label}</button>`).join('')}</nav>${content}</main>`;
}
function loginScreen(){ app.innerHTML=`<main class="login"><section class="auth-card"><div class="mark"><span class="logo">✓</span>Namichii Task</div><h1>Masuk ke ruang kerja</h1><p class="muted">Kelola tugas, bukti pekerjaan, dan persetujuan dalam satu tempat.</p><form id="login"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><p id="login-error" class="error" hidden></p><button class="btn full">Masuk</button></form><p class="hint">Gunakan akun Admin atau Staff yang sudah terdaftar.</p></section></main>`; document.querySelector('#login').onsubmit=login; }
async function login(e){ e.preventDefault(); const f=new FormData(e.currentTarget); const out=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')}); if(out.error){const n=document.querySelector('#login-error');n.textContent='Email atau password tidak dapat digunakan.';n.hidden=false;return;} session=out.data.session; await bootstrap(); }
async function bootstrap(){ const {data:{session:s}}=await supabase.auth.getSession(); session=s; if(!session){loginScreen();return;} const {data,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).single(); if(error||!data?.active){ await supabase.auth.signOut(); loginScreen(); toast('Akun tidak aktif atau profil belum tersedia.',true); return;} profile=data; await loadData(); render(); }
async function loadData(){
  const tasksQuery=supabase.from('tasks').select('*, task_checklists(*), task_reports(*), task_attachments(*), task_approvals(*)').order('created_at',{ascending:false});
  const [t, people]=await Promise.all([tasksQuery, isAdmin()?supabase.from('profiles').select('*').order('full_name'):Promise.resolve({data:[]})]);
  if(t.error) throw t.error; tasks=t.data||[]; staff=people.data||[];
}
function dashboard(){const mine=tasks; const count=s=>mine.filter(t=>t.status===s).length; return shell(`<section class="page-head"><div><h1>Selamat datang, ${esc(profile.full_name?.split(' ')[0]||'') }</h1><p>${isAdmin()?'Pantau pekerjaan tim dan selesaikan verifikasi.':'Fokus pada tugas yang perlu Anda selesaikan.'}</p></div>${isAdmin()?'<button class="btn" data-action="new-task">+ Buat tugas</button>':''}</section><section class="grid summary"><article class="card metric"><span>Total tugas</span><b>${mine.length}</b></article><article class="card metric"><span>Dikerjakan</span><b>${count('work')+count('revise')}</b></article><article class="card metric"><span>Perlu verifikasi</span><b>${count('review')}</b></article><article class="card metric"><span>Selesai</span><b>${count('done')}</b></article></section><section class="card" style="margin-top:16px"><h2 class="section-title">${isAdmin()?'Tugas terbaru':'Prioritas Anda'}</h2>${taskList(mine.slice(0,5))}</section>`);}
function taskList(list){ if(!list.length)return '<div class="empty">Belum ada tugas di sini.</div>'; return `<div class="task-list">${list.map(t=>`<article class="task"><div class="task-top"><div><h3>${esc(t.title)}</h3><div class="meta"><span>Deadline: ${date(t.deadline)}</span>${isAdmin()?`<span>Staff: ${esc(staff.find(p=>p.id===t.staff_id)?.full_name||'—')}</span>`:''}</div></div>${status(t.status)}</div>${progressBar(t)}${t.description?`<p>${esc(t.description)}</p>`:''}<div class="actions"><button class="btn secondary" data-task="${t.id}">Buka detail</button></div></article>`).join('')}</div>`;}
function tasksPage(){return shell(`<section class="page-head"><div><h1>${isAdmin()?'Semua tugas':'Tugas saya'}</h1><p>Perbarui checklist dan pantau status pekerjaan.</p></div>${isAdmin()?'<button class="btn" data-action="new-task">+ Buat tugas</button>':''}</section>${taskList(tasks)}`);}
function reportsPage(){const rows=tasks.filter(t=>t.report||t.task_approvals?.length).flatMap(t=>[{t, report:t.report, approval:t.task_approvals?.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]}]);return shell(`<section class="page-head"><div><h1>Laporan & review</h1><p>${isAdmin()?'Semua laporan yang menunggu atau sudah diverifikasi.':'Riwayat laporan pekerjaan Anda.'}</p></div></section><section class="card table-wrap">${rows.length?`<table><thead><tr><th>Tugas</th><th>Laporan</th><th>Status</th><th>Keputusan</th></tr></thead><tbody>${rows.map(({t,report,approval})=>`<tr><td><button class="btn secondary" data-task="${t.id}">${esc(t.title)}</button></td><td>${esc(report||'—')}</td><td>${status(t.status)}</td><td>${approval?`${approval.decision==='approved'?'Disetujui':'Revisi'}${approval.note?`: ${esc(approval.note)}`:''}`:'—'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Belum ada laporan untuk ditampilkan.</div>'}</section>`);}
function peoplePage(){return shell(`<section class="page-head"><div><h1>Manajemen Staff</h1><p>Aktifkan akun dan tentukan peran Admin atau Staff.</p></div></section><section class="card">${staff.map(p=>`<div class="staff-row"><div><b>${esc(p.full_name||'Tanpa nama')}</b><div class="muted">${p.id===profile.id?'Akun Anda · ':''}${p.active?'Aktif':'Nonaktif'}</div></div><div class="actions"><select data-role="${p.id}" aria-label="Peran ${esc(p.full_name)}"><option value="staff" ${p.role==='staff'?'selected':''}>Staff</option><option value="admin" ${p.role==='admin'?'selected':''}>Admin</option></select><button class="btn secondary" data-action="save-person" data-id="${p.id}" data-active="${p.active}">Simpan</button><button class="btn ${p.active?'danger':'secondary'}" data-action="toggle-person" data-id="${p.id}" data-active="${p.active}">${p.active?'Nonaktifkan':'Aktifkan'}</button></div></div>`).join('')}</section>`);}
function render(){try{let body=view==='dashboard'?dashboard():view==='tasks'?tasksPage():view==='reports'?reportsPage():peoplePage();app.innerHTML=body;bind();}catch(e){err(e);}}
function bind(){document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{view=x.dataset.view;render();});document.querySelector('[data-action="logout"]')?.addEventListener('click',async()=>{await supabase.auth.signOut();session=null;profile=null;loginScreen();});document.querySelectorAll('[data-task]').forEach(x=>x.onclick=()=>openTask(x.dataset.task));document.querySelectorAll('[data-action="new-task"]').forEach(x=>x.onclick=newTaskModal);document.querySelectorAll('[data-action="save-person"]').forEach(x=>x.onclick=()=>savePerson(x.dataset.id,x.dataset.active==='true'));document.querySelectorAll('[data-action="toggle-person"]').forEach(x=>x.onclick=()=>savePerson(x.dataset.id,x.dataset.active!=='true'));}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><section class="modal-card"><button class="close" data-action="close-modal" aria-label="Tutup">×</button>${html}</section></div>`);document.querySelector('[data-action="close-modal"]').onclick=closeModal;}
function closeModal(){document.querySelector('#modal')?.remove();selected=null;}
function newTaskModal(){if(!isAdmin())return; modal(`<h2>Buat tugas baru</h2><p class="muted">Tugaskan pekerjaan dan siapkan checklist awal.</p><form id="task-form"><label>Judul tugas<input name="title" required maxlength="160"></label><label>Deskripsi<textarea name="description" placeholder="Instruksi atau konteks pekerjaan"></textarea></label><div class="row"><label>Staff<select name="staff_id" required><option value="">Pilih staff</option>${staff.filter(p=>p.active&&p.role==='staff').map(p=>`<option value="${p.id}">${esc(p.full_name||p.id)}</option>`).join('')}</select></label><label>Deadline<input name="deadline" type="datetime-local"></label></div><label>Checklist & poin (satu per baris)<textarea name="checks" required placeholder="Foto area sebelum bekerja | 10&#10;Bersihkan peralatan | 30&#10;Laporan akhir | 60"></textarea></label><p class="hint">Format: nama checklist | poin. Jika poin kosong, nilainya 1.</p><button class="btn full">Buat & tugaskan</button></form>`);document.querySelector('#task-form').onsubmit=createTask;}
async function createTask(e){e.preventDefault();const f=new FormData(e.currentTarget), checks=String(f.get('checks')).split('\n').map(line=>{const [item,raw]=line.split('|');const score=raw?.trim()===''||raw===undefined?1:Number(raw.trim());return {item:item.trim(),score};}).filter(x=>x.item);if(!checks.length){toast('Masukkan minimal satu item checklist.',true);return;}if(checks.some(x=>!Number.isInteger(x.score)||x.score<1||x.score>100)){toast('Poin tiap checklist harus bilangan 1–100.',true);return;}try{const {data:t,error}=await supabase.from('tasks').insert({title:f.get('title').trim(),description:f.get('description').trim()||null,staff_id:f.get('staff_id'),created_by:session.user.id,deadline:f.get('deadline')?new Date(f.get('deadline')).toISOString():null,status:'work'}).select().single();if(error)throw error;const {error:ce}=await supabase.from('task_checklists').insert(checks.map(x=>({task_id:t.id,item:x.item,score:x.score})));if(ce)throw ce;closeModal();await refresh('Tugas berhasil ditugaskan.');}catch(e){err(e);}}
async function openTask(id){selected=tasks.find(t=>t.id===id);if(!selected)return;const t=selected, checks=t.task_checklists||[], approvals=(t.task_approvals||[]).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)), attachments=t.task_attachments||[];modal(`<h2>${esc(t.title)}</h2><div class="meta"><span>${status(t.status)}</span><span>Deadline: ${date(t.deadline)}</span></div><div class="split" style="margin-top:16px"><section><h3 class="section-title">Checklist (${checks.filter(c=>c.completed).length}/${checks.length})</h3>${checks.map(c=>`<label class="check ${c.completed?'done':''}"><input type="checkbox" data-check="${c.id}" ${c.completed?'checked':''} ${isAdmin()||t.status==='review'||t.status==='done'?'disabled':''}><span>${esc(c.item)}</span></label>`).join('')||'<p class="muted">Tidak ada checklist.</p>'}${!isAdmin()&&['work','revise'].includes(t.status)?'<button class="btn secondary" data-action="add-check">+ Tambah checklist</button>':''}<h3 class="section-title" style="margin-top:20px">Bukti pekerjaan</h3>${attachments.map(a=>`<div class="attachment"><span>📎 ${esc(a.storage_path.split('/').pop())}</span><button class="btn secondary" data-file="${esc(a.storage_path)}">Lihat</button></div>`).join('')||'<p class="muted">Belum ada bukti.</p>'}${!isAdmin()&&['work','revise'].includes(t.status)?'<label class="btn secondary" style="display:inline-block">Upload bukti<input id="evidence" type="file" accept="image/*,.pdf" hidden></label>':''}</section><section><h3 class="section-title">Laporan pekerjaan</h3>${t.report?`<p>${esc(t.report)}</p>`:'<p class="muted">Belum ada laporan.</p>'}${approvals.map(a=>`<div class="review-note"><b>${a.decision==='approved'?'Disetujui':'Perlu revisi'}</b><br>${esc(a.note||'Tanpa catatan')}<br><small>${date(a.created_at)}</small></div>`).join('')}${!isAdmin()&&['work','revise'].includes(t.status)?`<form id="submit-report"><label>Laporan<textarea name="report" placeholder="Jelaskan hasil pekerjaan"></textarea></label><button class="btn full">Kirim untuk verifikasi</button></form>`:''}${isAdmin()&&t.status==='review'?`<form id="review-form"><label>Catatan review<textarea name="note" placeholder="Opsional untuk setuju, wajib untuk revisi"></textarea></label><div class="actions"><button class="btn" name="decision" value="approve">Setujui & selesai</button><button class="btn danger" name="decision" value="reject">Minta revisi</button></div></form>`:''}</section></div>`);document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>toggleCheck(x.dataset.check,x.checked));document.querySelectorAll('[data-file]').forEach(x=>x.onclick=()=>openEvidence(x.dataset.file));document.querySelector('[data-action="add-check"]')?.addEventListener('click',addChecklist);document.querySelector('#evidence')?.addEventListener('change',uploadEvidence);document.querySelector('#submit-report')?.addEventListener('submit',submitReport);document.querySelector('#review-form')?.addEventListener('submit',reviewTask);}
async function toggleCheck(id, completed){try{const {error}=await supabase.from('task_checklists').update({completed,completed_at:completed?new Date().toISOString():null}).eq('id',id);if(error)throw error;await reloadSelected();}catch(e){err(e);}}
async function addChecklist(){const item=prompt('Tulis item checklist baru:');if(!item?.trim())return;try{const {error}=await supabase.from('task_checklists').insert({task_id:selected.id,item:item.trim()});if(error)throw error;await reloadSelected();}catch(e){err(e);}}
async function uploadEvidence(e){const file=e.target.files?.[0];if(!file)return;if(file.size>10*1024*1024){toast('Ukuran berkas maksimal 10 MB.',true);return;}const filename=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${selected.id}/${session.user.id}/${Date.now()}-${filename}`;try{toast('Mengunggah bukti…');const {error:up}=await supabase.storage.from('task-evidence').upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;const {error:db}=await supabase.from('task_attachments').insert({task_id:selected.id,uploaded_by:session.user.id,storage_path:path});if(db)throw db;await reloadSelected();toast('Bukti berhasil diunggah.');}catch(e){err(e);}}
async function openEvidence(path){try{const {data,error}=await supabase.storage.from('task-evidence').createSignedUrl(path,300);if(error)throw error;window.open(data.signedUrl,'_blank','noopener');}catch(e){err(e);}}
async function submitReport(e){e.preventDefault();try{const report=new FormData(e.currentTarget).get('report');const {error}=await supabase.rpc('submit_task_for_review',{p_task_id:selected.id,p_report:report});if(error)throw error;closeModal();await refresh('Laporan dikirim untuk verifikasi.');}catch(e){err(e);}}
async function reviewTask(e){e.preventDefault();try{const f=new FormData(e.currentTarget),decision=e.submitter?.value,note=String(f.get('note')||'').trim();if(decision==='reject'&&!note){toast('Catatan revisi wajib diisi.',true);return;}const {error}=await supabase.rpc(decision==='approve'?'approve_task':'reject_task',{p_task_id:selected.id,p_note:note||null});if(error)throw error;closeModal();await refresh(decision==='approve'?'Tugas disetujui dan selesai.':'Tugas dikembalikan untuk revisi.');}catch(e){err(e);}}
async function savePerson(id,active){try{const role=document.querySelector(`[data-role="${id}"]`).value;if(id===profile.id&&!active){toast('Anda tidak dapat menonaktifkan akun sendiri.',true);return;}const {error}=await supabase.from('profiles').update({role,active}).eq('id',id);if(error)throw error;await refresh('Profil staff diperbarui.');}catch(e){err(e);}}
async function reloadSelected(){const id=selected.id;await loadData();await openTask(id);}
async function refresh(message){await loadData();render();if(message)toast(message);}
supabase.auth.onAuthStateChange((_event,s)=>{if(!s&&!session)loginScreen();});
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
bootstrap().catch(e=>{err(e);loginScreen();});

// Checklist scoring: the last declarations intentionally provide the scored task view.
async function openTask(id){
  selected=tasks.find(t=>t.id===id); if(!selected)return;
  const t=selected, checks=t.task_checklists||[], approvals=(t.task_approvals||[]).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)), attachments=t.task_attachments||[];
  const editable=!isAdmin()&&['work','revise'].includes(t.status), canAdd=isAdmin()||editable;
  modal(`<h2>${esc(t.title)}</h2><div class="meta"><span>${status(t.status)}</span><span>Deadline: ${date(t.deadline)}</span></div><div class="split" style="margin-top:16px"><section><h3 class="section-title">Checklist (${checks.filter(c=>c.completed).length}/${checks.length})</h3>${progressBar(t)}${checks.map(c=>`<label class="check ${c.completed?'done':''}"><input type="checkbox" data-check="${c.id}" ${c.completed?'checked':''} ${!editable?'disabled':''}><span>${esc(c.item)} <small class="score">(${Number(c.score||1)} poin)</small></span></label>`).join('')||'<p class="muted">Tidak ada checklist.</p>'}${canAdd?'<button class="btn secondary" data-action="add-check">+ Tambah checklist</button>':''}<h3 class="section-title" style="margin-top:20px">Bukti pekerjaan</h3>${attachments.map(a=>`<div class="attachment"><span>📎 ${esc(a.storage_path.split('/').pop())}</span><button class="btn secondary" data-file="${esc(a.storage_path)}">Lihat</button></div>`).join('')||'<p class="muted">Belum ada bukti.</p>'}${editable?'<label class="btn secondary" style="display:inline-block">Upload bukti<input id="evidence" type="file" accept="image/*,.pdf" hidden></label>':''}</section><section><h3 class="section-title">Laporan pekerjaan</h3>${t.report?`<p>${esc(t.report)}</p>`:'<p class="muted">Belum ada laporan.</p>'}${approvals.map(a=>`<div class="review-note"><b>${a.decision==='approved'?'Disetujui':'Perlu revisi'}</b><br>${esc(a.note||'Tanpa catatan')}<br><small>${date(a.created_at)}</small></div>`).join('')}${editable?`<form id="submit-report"><label>Laporan<textarea name="report" placeholder="Jelaskan hasil pekerjaan"></textarea></label><button class="btn full">Kirim untuk verifikasi</button></form>`:''}${isAdmin()&&t.status==='review'?`<form id="review-form"><label>Catatan review<textarea name="note" placeholder="Opsional untuk setuju, wajib untuk revisi"></textarea></label><div class="actions"><button class="btn" name="decision" value="approve">Setujui & selesai</button><button class="btn danger" name="decision" value="reject">Minta revisi</button></div></form>`:''}</section></div>`);
  document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>toggleCheck(x.dataset.check,x.checked));
  document.querySelectorAll('[data-file]').forEach(x=>x.onclick=()=>openEvidence(x.dataset.file));
  document.querySelector('[data-action="add-check"]')?.addEventListener('click',addChecklist);
  document.querySelector('#evidence')?.addEventListener('change',uploadEvidence);
  document.querySelector('#submit-report')?.addEventListener('submit',submitReport);
  document.querySelector('#review-form')?.addEventListener('submit',reviewTask);
}
async function addChecklist(){
  const item=prompt('Tulis item checklist baru:'); if(!item?.trim())return;
  let score=1;
  if(isAdmin()){const raw=prompt('Bobot poin (1–100):','1'); if(raw===null)return; score=Number(raw); if(!Number.isInteger(score)||score<1||score>100){toast('Poin harus bilangan 1–100.',true);return;}}
  try{const {error}=await supabase.from('task_checklists').insert({task_id:selected.id,item:item.trim(),score});if(error)throw error;await reloadSelected();}catch(e){err(e);}
}

